apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME} # Change this to your app name
  namespace: m324-2 
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: ${APP_NAME} # Change this to your app name
