name: ci

on: [push]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shanthosh04
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
          secrets: |
            "dckr_pat_6noar5fTKXu0FbXBw1vhHwELatw"
